const List<String> kFunFacts = [
  'Saudara seibu, baik laki-laki maupun perempuan, mendapat bagian yang sama besar — berbeda dari saudara kandung.',
  'Wasiat dalam Islam maksimal hanya boleh 1/3 dari total harta bersih setelah hutang dan pengurusan jenazah.',
  'Hutang pewaris wajib dilunasi terlebih dahulu sebelum harta warisan dibagikan ke ahli waris.',
  'Perbedaan agama menghalangi hak waris — pewaris muslim dan ahli waris non-muslim tidak saling mewarisi.',
  'Seseorang yang membunuh pewaris kehilangan haknya sebagai ahli waris, meski masih memiliki hubungan kerabat.',
  'Anak angkat tidak termasuk ahli waris dalam hukum faraidh, haknya hanya bisa lewat jalur wasiat.',
  'Zaid bin Tsabit dikenal sebagai salah satu sahabat Nabi yang paling menguasai ilmu faraidh.',
  'Hak waris seseorang ditentukan oleh syariat, bukan berdasarkan siapa yang paling dekat secara emosional.',
  'Laki-laki dan perempuan sama-sama dapat menjadi ahli waris sesuai ketentuan syariat.',
  'Pembagian warisan baru dilakukan setelah pewaris benar-benar wafat.',
  'Kecilnya harta ahli waris tidak memengaruhi besaran porsi yang diterima ahli waris.',
  'Waris dalam Islam bukan hanya membahas harta, tetapi juga menjaga keadilan dan tanggung jawab dalam keluarga.',
  'Hubungan nasab dan pernikahan merupakan dua sebab utama seseorang dapat memperoleh hak waris.',
  'Pembagian warisan yang benar dapat membantu mengurangi potensi perselisihan dalam keluarga.',
  'Tidak semua cucu otomatis memperoleh bagian warisan; haknya bergantung pada kondisi ahli waris lainnya.',
  'Mencatat harta, hutang, dan wasiat semasa hidup dapat mempermudah proses pembagian warisan.',
  'Warisan tidak hanya berupa uang, tetapi juga tanah, rumah, kendaraan, hingga hak kepemilikan lainnya.',
];
