const List<String> kFunFacts = [
  'Cucu bisa terhalang mendapat warisan jika masih ada anak laki-laki dari pewaris yang masih hidup.',
  'Istri mendapat 1/4 bagian jika suami tidak memiliki anak, dan 1/8 jika suami memiliki anak.',
  'Suami mendapat 1/2 bagian jika istri tidak memiliki anak, dan 1/4 jika istri memiliki anak.',
  'Anak laki-laki umumnya mendapat bagian dua kali lipat dari anak perempuan sebagai ashabah.',
  'Saudara seibu, baik laki-laki maupun perempuan, mendapat bagian yang sama besar — berbeda dari saudara kandung.',
  'Wasiat dalam Islam maksimal hanya boleh 1/3 dari total harta peninggalan, kecuali seluruh ahli waris menyetujui lebih.',
  'Hutang pewaris wajib dilunasi terlebih dahulu sebelum harta warisan dibagikan ke ahli waris.',
  'Ibu mendapat 1/6 bagian jika pewaris memiliki anak, atau memiliki dua saudara atau lebih.',
  'Ibu mendapat 1/3 bagian jika pewaris tidak memiliki anak maupun saudara.',
  'Ayah bisa berperan sebagai dzawil furud (1/6) sekaligus ashabah, tergantung ahli waris lain yang masih hidup.',
  'Perbedaan agama menghalangi hak waris — pewaris muslim dan ahli waris non-muslim tidak saling mewarisi.',
  'Seseorang yang membunuh pewaris kehilangan haknya untuk mewarisi, meski masih memiliki hubungan kerabat.',
  'Anak angkat tidak termasuk ahli waris dalam hukum faraidh, haknya hanya bisa lewat jalur wasiat.',
  'Saudara kandung bisa terhalang mendapat warisan jika pewaris masih memiliki ayah atau anak laki-laki.',
  'Cucu perempuan dari anak laki-laki bisa menggantikan posisi ayahnya jika sang ayah wafat lebih dulu dari pewaris.',
  "Al-'Aul terjadi ketika total bagian ahli waris melebihi 100%, sehingga tiap bagian disesuaikan secara proporsional.",
  "Ar-Radd adalah kebalikan dari Al-'Aul — sisa harta yang tidak habis dibagi dikembalikan proporsional ke ahli waris.",
  'Kakek dapat menggantikan posisi ayah dalam pembagian warisan apabila sang ayah telah wafat.',
  'Ilmu faraidh pernah disebut sebagai "setengah dari ilmu" karena kompleksitas dan besarnya kebutuhan akan ilmu ini.',
  'Zaid bin Tsabit dikenal sebagai salah satu sahabat Nabi yang paling menguasai ilmu pembagian warisan.',
];
